repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: prettier-markdown
        name: prettier markdown
        entry: prettier --write
        language: system
        types: [markdown]
      - id: uv-lock
        name: uv lock
        entry: bash -c 'cd backend && uv lock --check'
        language: system
        files: backend/pyproject.toml
        pass_filenames: false
      - id: ruff-check
        name: ruff check
        entry: bash -c 'cd backend && uv run ruff check --fix .'
        language: system
        files: backend/
        types: [python]
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        entry: bash -c 'cd backend && uv run ruff format .'
        language: system
        files: backend/
        types: [python]
        pass_filenames: false
      - id: dart-format
        name: dart format
        entry: dart format
        language: system
        types: [dart]
        files: frontend/survivor_pool/
        # Append command with list of staged files
        pass_filenames: true
      - id: flutter-analyze
        name: flutter analyze
        entry: bash -c 'cd frontend/survivor_pool && flutter analyze'
        language: system
        files: frontend/survivor_pool/
        # Run command exactly as written
        pass_filenames: false
      - id: pyright
        name: pyright
        entry: bash -c 'cd backend && pyright'
        language: system
        types: [python]
        files: backend/
        pass_filenames: false
