services:
  frontend:
    build:
      context: frontend/survivor_pool
      dockerfile: web/Dockerfile
      args:
        API_BASE_URL: http://localhost:8001
    ports:
      - "80:8080"
    restart: unless-stopped

  backend:
    build:
      context: backend
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - survivor-pool-network
    env_file:
      - .env.prod

  mongo:
    image: mongo:8.0
    container_name: survivor-mongo
    env_file:
      - .env.prod
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    restart: unless-stopped
    networks:
      - survivor-pool-network

volumes:
  mongo_data:
  mongo_config:

networks:
  survivor-pool-network:
